language: rust
rust:
  - nightly

matrix:
  include:
    - addons:
        apt:
          packages:
            - gcc-arm-none-eabi

install:
  - rustup target add thumbv7em-none-eabi

script:
  - cargo -v build --bins --features=no_device
  - cargo -v build --bins --features=all

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - develop
    - master
