language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - addons:
        apt:
          packages:
            - gcc-arm-none-eabi

install:
  - rustup target add thumbv7em-none-eabi

script:
  - ./travis.sh

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - develop
    - master
