language: rust

matrix:
  include:
    - addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      rust: stable
    - addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      rust: nightly

    - addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      rust: beta

install:
  - rustup target add thumbv7em-none-eabi

script:
  - ./travis.sh

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - develop
    - master
